// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package MyCalc

import "strconv"

type CalcType int8

const (
	CalcTypeSum     CalcType = 0
	CalcTypeAverage CalcType = 1
	CalcTypeMedian  CalcType = 2
)

var EnumNamesCalcType = map[CalcType]string{
	CalcTypeSum:     "Sum",
	CalcTypeAverage: "Average",
	CalcTypeMedian:  "Median",
}

var EnumValuesCalcType = map[string]CalcType{
	"Sum":     CalcTypeSum,
	"Average": CalcTypeAverage,
	"Median":  CalcTypeMedian,
}

func (v CalcType) String() string {
	if s, ok := EnumNamesCalcType[v]; ok {
		return s
	}
	return "CalcType(" + strconv.FormatInt(int64(v), 10) + ")"
}
